server:
  port: 8888
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://112.124.36.129/project?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: BeamLin123..
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    open: true  # 是否开启redis缓存  true开启   false关闭
    database: 0
    password:
    host: 112.124.36.129
    timeout: 6000ms  # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
storage:
  config:
    type: 2 # 特别特别重要，决定使用说明方式进行上传 1：七牛  2：阿里云  3：腾讯云   4：FastDFS   5：本地上传    6：minio
    qiniuDomain: http://7xqbwh.dl1.z0.glb.clouddn.com #七牛绑定的域名
    qiniuPrefix: upload #七牛路径前缀
    qiniuAccessKey:  #七牛ACCESS_KEY
    qiniuSecretKey: uIwJHevMRWU0VLxFvgy0tAcOdGqasdtVlJkdy6vV #七牛SECRET_KEY
    qiniuBucketName: #七牛存储空间名

    aliyunDomain: https://test-ossbeam.oss-cn-hangzhou.aliyuncs.com #阿里云绑定的域名
    aliyunPrefix: jpg #阿里云路径前缀
    aliyunEndPoint: oss-cn-hangzhou.aliyuncs.com #阿里云EndPoint
    aliyunAccessKeyId: LTAI5tCMKjR6GKy1zdPBHNRm #阿里云AccessKeyId
    aliyunAccessKeySecret: 2Z9lFR78kGdLggRExFHXrn9JFo9siJ #阿里云AccessKeySecret
    aliyunBucketName: test-ossbeam #阿里云BucketName


    tcloudDomain: #腾讯云绑定的域名
    tcloudPrefix: #腾讯云路径前缀
    tcloudAppId: #腾讯云AppId
    tcloudSecretId: #腾讯云SecretId
    tcloudSecretKey: #腾讯云SecretKey
    tcloudBucketName: #腾讯云BucketName
    tcloudRegion: #腾讯云COS所属地区

    fastdfsDomain: #FastDFS绑定的域名

    localDomain: #本地上传绑定的域名
    localPrefix: #本地上传路径前缀
    localPath: #本地上传存储目录

    minioEndPoint: #Minio EndPoint
    minioAccessKey: #accessKey
    minioSecretKey: #secretKey
    minioBucketName: #BucketName
    minioPrefix: #MinIO上传路径前缀

fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    - 192.168.10.12:22122